apiVersion: v1
kind: Service
metadata:
  name: rafsservice
  namespace: {{ $.Values.global.rafsservice.namespace }}
  annotations:
    {{- range $key, $value := $.Values.global.rafsservice.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: rafsservice
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: {{ $.Values.global.rafsservice.service.type }}