apiVersion: v1
kind: Service
metadata:
  name: rafs-service
  namespace: {{ $.Values.global.rafs-service.namespace }}
  annotations:
    {{- range $key, $value := $.Values.global.rafs-service.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    app: rafs-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: {{ $.Values.global.rafs-service.service.type }}