apiVersion: apps/v1
kind: Deployment
metadata:
  name: rafsservice
  namespace: {{ $.Values.global.rafsservice.namespace }}
spec:
  replicas: {{ $.Values.global.rafsservice.replicaCount }}
  selector:
    matchLabels:
      app: rafsservice
  template:
    metadata:
      labels:
        app: rafsservice
    spec:
      containers:
      - name: rafsservice
        image: {{ $.Values.global.rafsservice.image.repository }}/{{ $.Values.global.rafsservice.image.name }}:{{ $.Values.global.rafsservice.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        envFrom:
          - secretRef:
              name: sc-rediscache-secret
        env:
        - name: SERVICE_NAME
          value: "rafs-ddms"
        - name: DDMS_ID
          value: "rafs"
        - name: OPENAPI_PREFIX
          value: {{ $.Values.global.rafsservice.configuration.OPENAPI_PREFIX }}
        - name: CACHE_ENABLED
          value: {{ $.Values.global.rafsservice.configuration.REDIS_CACHE_ENABLED }}
        - name: URL_PREFIX
          value: {{ $.Values.global.rafsservice.configuration.URL_PREFIX }}
        - name: CLOUD_PROVIDER
          value: "Azure"
        - name: SERVICE_HOST_STORAGE
          value: {{ $.Values.global.rafsservice.configuration.ADME_ENDPOINT | cat "api/storage/v2" }}
        - name: SERVICE_HOST_SCHEMA
          value: {{ $.Values.global.rafsservice.configuration.ADME_ENDPOINT | cat "api/schema-service/v1" }}
        - name: SERVICE_HOST_PARTITION
          value: {{ $.Values.global.rafsservice.configuration.ADME_ENDPOINT | cat "api/partition/v1" }}
        - name: SERVICE_HOST_DATASET
          value: {{ $.Values.global.rafsservice.configuration.ADME_ENDPOINT | cat "api/dataset/v1" }}  
        - name: SERVICE_HOST_LEGAL
          value: {{ $.Values.global.rafsservice.configuration.ADME_ENDPOINT | cat "api/legal/v1" }}
        - name: REQUEST_TIMEOUT
          value: '"180"'
        - name: LOGGING_LEVEL
          value: {{ $.Values.global.rafsservice.configuration.LOGGING_LEVEL }}
        - name: CACHE_ENABLE
          value: {{ $.Values.global.rafsservice.configuration.REDIS_CACHE_ENABLED }}
        - name: CACHE_BACKEND
          value: app.core.helpers.cache.backends.redis_cache.RedisCacheBackend
        - name: PARTITION
          value: {{ $.Values.global.rafsservice.configuration.ADME_DATA_PARTITION }}
        - name: PYTHONBUFFERED
          value: "1"
        
        