swagger: '2.0'
info:
  description: Notification Service  
  version: '1.0'
  title: Notification Service
tags:
  - name: global-error-controller
    description: Global Error Controller
  - name: info-api
    description: Info Api
  - name: pubsub-endpoint
    description: Pubsub Endpoint
basePath: /api/notification/v1
paths:  
  /error:
    get:
      tags:
        - global-error-controller
      summary: handleErrorGet
      operationId: handleErrorGetUsingGET
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
    post:
      tags:
        - global-error-controller
      summary: handleErrorPost
      operationId: handleErrorPostUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
    put:
      tags:
        - global-error-controller
      summary: handleErrorPut
      operationId: handleErrorPutUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
    delete:
      tags:
        - global-error-controller
      summary: handleErrorDelete
      operationId: handleErrorDeleteUsingDELETE
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - Bearer: []
    patch:
      tags:
        - global-error-controller
      summary: handleErrorPatch
      operationId: handleErrorPatchUsingPATCH
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - Bearer: []
  /info:
    get:
      tags:
        - info-api
      summary: info
      operationId: infoUsingGET
      produces:
        - application/json
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/VersionInfo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
  /push-handlers/records-changed:
    post:
      tags:
        - pubsub-endpoint
      summary: recordChanged
      operationId: recordChangedUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: header
          name: data-partition-id
          description: tenant
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Bearer: []
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ConnectedOuterService:
    type: object
    properties:
      name:
        type: string
      version:
        type: string
    title: ConnectedOuterService
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  VersionInfo:
    type: object
    properties:
      artifactId:
        type: string
      branch:
        type: string
      buildTime:
        type: string
      commitId:
        type: string
      commitMessage:
        type: string
      connectedOuterServices:
        type: array
        items:
          $ref: '#/definitions/ConnectedOuterService'
      groupId:
        type: string
      version:
        type: string
    title: VersionInfo
