apiVersion: apps/v1
kind: Deployment
metadata:
  name: etpserver
  namespace: {{ $.Values.global.etpserver.namespace }}
spec:
  replicas: {{ $.Values.global.etpserver.replicaCount }}
  selector:
    matchLabels:
      app: etpserver
  template:
    metadata:
      labels:
        app: etpserver
    spec:
      containers:
      - name: etpserver
        image: {{ $.Values.global.etpserver.image.repository }}/{{ $.Values.global.etpserver.image.name }}:{{ $.Values.global.etpserver.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9002
          protocol: TCP
        command: [ "openETPServer", "server", "--start", "--log_level", "debug", "--port", "9002", "--authZ", "delegate=https://demo.energy.azure.com", "--authN", "none" ]
        env:
        - name: RDMS_DATA_PARTITION_MODE
          value: {{ $.Values.global.etpserver.configuration.RDMS_DATA_PARTITION_MODE }}
        - name: RDMS_DATA_CONNECTIVITY_MODE
          value: {{ $.Values.global.etpserver.configuration.RDMS_DATA_CONNECTIVITY_MODE }}
        - name: DOMAIN_NAME
          value: {{ $.Values.global.etpserver.configuration.DOMAIN_NAME }}
        - name: POSTGRESQL_CONN_STRING
          value: {{ $.Values.global.etpserver.configuration.POSTGRESQL_CONN_STRING }}
